### ISSUE TITLE
Need to find SUT for examples

### ISSUE THREAD

**Issue by budabum** [griddynamics/screen-object#1]
Need to find SUT for examples: ideally simple Web App to play with and with ability to easily extend to test some complicated cases.
Should be easy to setup/deploy/configure. Best case - to stratup from tests/examples in embedded web server.

**Comment by gryabov** [comment]
I can solve this issue by the next two approaches:

**First one** is using booted version of spring pet clinic example: 
- https://github.com/arnaldop/enhanced-pet-clinic

Pros: Lightweight. All you need to start up the SUT is a jar file. Easy to extend.
Cons: Not e-commerce example. 

**The second one** is by using an opencart e-commerce demo site embedded into a docker container:
- https://hub.docker.com/r/chrisss404/opencart/

I tried this one and it is good for me.
Pros: e-commerce example. 
Cons: You have to set up a docker and a docker-compose. 

I used this manual to install it on ubuntu https://docs.docker.com/engine/installation/linux/ubuntulinux/

We have to choose one!
